name: counter_repository
description: A Dart Package to handle counter domain.
version: 1.0.0

environment:
  sdk: ^3.1.2

# Add regular dependencies here.
dependencies:
  equatable: ^2.0.5
  meta: ^1.10.0
  rxdart: ^0.27.7

dev_dependencies:
  lints: ^2.0.0
  mocktail: ^1.0.0
  test: ^1.21.0
